# Generated by Django 3.2.7 on 2021-11-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAllAuthForm', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
